apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-d
spec:
  selector:
    matchLabels:
      app: api-d
  template:
    metadata:
      labels:
        app: api-d
    spec:
      containers:
      - name: api-d
        image: vitorrafael/k8s-api:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-d-svc
spec:
  type: NodePort
  selector:
    app: api-d
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000