apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-d
spec:
  selector:
    matchLabels:
      app: api-d
  template:
    metadata:
      labels:
        app: api-d
    spec:
      containers:
      - name: api-d
        image: vitorrafael/k8s-api:v5
        ports:
        - containerPort: 8080
        env:
          - name: MONGO_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: MONGO_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-d-svc
spec:
  type: NodePort
  selector:
    app: api-d
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000