apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    name: mongodb-pod
spec:
  containers:
  - name: mongodb-pod
    image: mongo:4.2.8
    ports:
      - containerPort: 27017
    volumeMounts:
      - name: data
        mountPath: /data/db
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-srv
spec:
  type: NodePort
  selector:
    name: mongodb-pod
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32001
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /Users/vitorrafael/Dev/fiap-software-architecture/f2/k8s/infra/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
