apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    name: api-pod
spec:
  containers:
  - name: api-pod
    image: vitorrafael/k8s-api:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: NodePort
  selector:
    name: api-pod
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31000